


CREATE TABLE EMPLOYEE (
    EMPID INT PRIMARY KEY NOT NULL, 
    MANID INT,
    FIRSTNAME VARCHAR2(30) NOT NULL,
    LASTNAME VARCHAR2(30) NOT NULL
); 

CREATE TABLE EMP_REIMB (
    EMPID INTEGER NOT NULL,
    REIMBID INTEGER UNIQUE NOT NULL
);
    
CREATE TABLE REIMB (

    MANID INTEGER NOT NULL,
    EMPID INTEGER NOT NULL, 
    REIMBID INTEGER PRIMARY KEY,
	AMOUNT NUMBER,
	STATUS VARCHAR2(30),
	IMAGE BLOB 
    ); 
    
CREATE TABLE EMPCONTACT (
    EMPID INTEGER NOT NULL, 
	ADDRESS VARCHAR2(30),
    CITY VARCHAR2(30), 
    ST VARCHAR2(30),
    EMAIL VARCHAR2(30),
    PHONE INTEGER
    ); 
    
CREATE TABLE REPORT_TO (
    EMPID INT NOT NULL, 
	MANAGERID INT
    ); 

ALTER TABLE EMP_REIMB
    ADD CONSTRAINT FK_EMP_REIMB
    FOREIGN KEY (EMPID) 
    REFERENCES EMPLOYEE(EMPID)
ON DELETE CASCADE; 

ALTER TABLE EMP_REIMB
    ADD CONSTRAINT FK_REIMB_ACCOUNT
    FOREIGN KEY (REIMBID) 
    REFERENCES REIMB(REIMBID)
ON DELETE CASCADE; 

ALTER TABLE EMPCONTACT
    ADD CONSTRAINT FK_CONTACT_EMP
    FOREIGN KEY (EMPID) 
    REFERENCES EMPLOYEE(EMPID)
ON DELETE CASCADE;

ALTER TABLE REPORT_TO
    ADD CONSTRAINT FK_REPORT_EMP
    FOREIGN KEY (EMPID) 
    REFERENCES EMPLOYEE(EMPID)
ON DELETE CASCADE;

ALTER TABLE EMPLOYEE
ADD TITLE VARCHAR2(30);

INSERT INTO EMPLOYEE
VALUES (1, NULL, 'Joe', 'Schmoe', 'Front Desk Coordinator');

INSERT INTO EMPLOYEE
VALUES (2, 201, 'Mehta', 'Sacheen','Doctor');

INSERT INTO EMPLOYEE
VALUES (3, 301, 'Doug', 'Conner','Physician Assistant');

INSERT INTO EMPLOYEE
VALUES (4, 101, 'Kathy', 'Wornick','Office Manager');

INSERT INTO EMPLOYEE
VALUES (5, 102, 'Cassie', 'Babarovic','Billing Manager');

INSERT INTO EMPLOYEE
VALUES (6, 203, 'Virendra', 'Patel','Doctor');

INSERT INTO EMPLOYEE
VALUES (7, NULL, 'Tracy', 'Samuelson','Medical Assistant');

INSERT INTO EMPCONTACT
VALUES (2, '2600 Regal Rd', 'Plano', 'Texas','Danny.trev21@gmail.com', 8001234567);

INSERT INTO EMPCONTACT
VALUES (3, '3800 Waterview Pkwy', 'Richardson', 'Texas','myDougie420@gmail.com', 3131234567);

INSERT INTO EMPCONTACT
VALUES (4, '901 Shelby Dr', 'Dallas', 'Texas','lookalive@gmail.com', 2148259924);

INSERT INTO EMPCONTACT
VALUES (5, 'P. Sherman 42 Wallaby Way', 'Sydney', 'Texas','iRememberedItAgain@gmail.com', 9727121225);

CREATE TABLE EMPLOGIN (
    EMPID INTEGER NOT NULL, 
    USERNAME VARCHAR2(30),
    PASS VARCHAR2(30) NOT NULL
); 

ALTER TABLE EMPLOGIN
    ADD CONSTRAINT FK_LOGIN_EMP
    FOREIGN KEY (EMPID) 
    REFERENCES EMPLOYEE(EMPID)
ON DELETE CASCADE;

DROP TABLE EMP_REIMB; 


SELECT *
FROM EMPLOYEE

SELECT MANID
FROM EMPLOYEE 
WHERE EMPID = 1; 

INSERT INTO EMPLOGIN VALUES (1, 'JSchmoe01', 'password'); 


INSERT INTO EMPLOGIN VALUES (2, 'MSacheen', 'theDoc'); 

SELECT EMPID
FROM EMPLOGIN 
WHERE USERNAME = 'MSacheen' AND PASS = 'theDoc'; 
